version: "3.8"
services:
  real_chatapi.api:
    build:
      context: .
      dockerfile: Presentation/Real_ChatApiReal_ChatApi.aApi/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgresdb
      - redis


  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: realChat@gmail.com
      PGADMIN_DEFAULT_PASSWORD: adminChat
    volumes:
      - pgadmin_data:/var/lib/pgadmin   
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  real_chatapi.webui:
    image: ${DOCKER_REGISTRY-}realchatapiwebui
    build:
      context: .
      dockerfile: Frontend/Real_ChatApi.webUI/Dockerfile
    ports:
      - "5291:5291"
    depends_on:
      - real_chatapi.api
volumes:
  postgres_data:
  pgadmin_data:


